/**
 * Every error the API can return has a stable machine readable code. Clients
 * switch on the code and render their own localised message, so the English
 * text in a response is only a developer-facing fallback.
 */
export const ERROR_CODES = {
  // Generic
  VALIDATION_FAILED: 'VALIDATION_FAILED',
  INTERNAL_ERROR: 'INTERNAL_ERROR',
  NOT_FOUND: 'NOT_FOUND',
  FORBIDDEN: 'FORBIDDEN',
  UNAUTHORIZED: 'UNAUTHORIZED',
  RATE_LIMIT_EXCEEDED: 'RATE_LIMIT_EXCEEDED',
  BAD_REQUEST: 'BAD_REQUEST',

  // Auth
  EMAIL_ALREADY_IN_USE: 'EMAIL_ALREADY_IN_USE',
  USERNAME_ALREADY_IN_USE: 'USERNAME_ALREADY_IN_USE',
  INVALID_CREDENTIALS: 'INVALID_CREDENTIALS',
  INVALID_REFRESH_TOKEN: 'INVALID_REFRESH_TOKEN',
  ACCOUNT_SUSPENDED: 'ACCOUNT_SUSPENDED',
  ACCESS_TOKEN_EXPIRED: 'ACCESS_TOKEN_EXPIRED',
  INSUFFICIENT_ROLE: 'INSUFFICIENT_ROLE',
  INVALID_RESET_TOKEN: 'INVALID_RESET_TOKEN',
  RESET_TOKEN_EXPIRED: 'RESET_TOKEN_EXPIRED',
  CURRENT_PASSWORD_INVALID: 'CURRENT_PASSWORD_INVALID',
  INVALID_AVATAR_URL: 'INVALID_AVATAR_URL',
  INVALID_VERIFICATION_TOKEN: 'INVALID_VERIFICATION_TOKEN',
  VERIFICATION_TOKEN_EXPIRED: 'VERIFICATION_TOKEN_EXPIRED',
  EMAIL_ALREADY_VERIFIED: 'EMAIL_ALREADY_VERIFIED',

  // Users
  USER_NOT_FOUND: 'USER_NOT_FOUND',

  // Games
  GAME_NOT_FOUND: 'GAME_NOT_FOUND',
  GAME_ALREADY_EXISTS: 'GAME_ALREADY_EXISTS',
  PLATFORM_NOT_FOUND: 'PLATFORM_NOT_FOUND',
  GENRE_NOT_FOUND: 'GENRE_NOT_FOUND',
  PLATFORM_NOT_AVAILABLE_FOR_GAME: 'PLATFORM_NOT_AVAILABLE_FOR_GAME',

  // Reviews
  REVIEW_NOT_FOUND: 'REVIEW_NOT_FOUND',
  REVIEW_ALREADY_EXISTS: 'REVIEW_ALREADY_EXISTS',
  REVIEW_NOT_OWNED: 'REVIEW_NOT_OWNED',
  CANNOT_VOTE_OWN_REVIEW: 'CANNOT_VOTE_OWN_REVIEW',
  VOTE_NOT_FOUND: 'VOTE_NOT_FOUND',
  CANNOT_REPORT_OWN_REVIEW: 'CANNOT_REPORT_OWN_REVIEW',
  REVIEW_ALREADY_REPORTED: 'REVIEW_ALREADY_REPORTED',
  REVIEW_REJECTED_AS_SPAM: 'REVIEW_REJECTED_AS_SPAM',
  REVIEW_RATE_LIMIT_EXCEEDED: 'REVIEW_RATE_LIMIT_EXCEEDED',
  INVALID_CURSOR: 'INVALID_CURSOR',

  // Moderation
  REPORT_NOT_FOUND: 'REPORT_NOT_FOUND',
  REPORT_ALREADY_RESOLVED: 'REPORT_ALREADY_RESOLVED',
  REVIEW_BOMB_EVENT_NOT_FOUND: 'REVIEW_BOMB_EVENT_NOT_FOUND',

  // Integrations
  IGDB_NOT_CONFIGURED: 'IGDB_NOT_CONFIGURED',
  IGDB_REQUEST_FAILED: 'IGDB_REQUEST_FAILED',
  IGDB_GAME_NOT_FOUND: 'IGDB_GAME_NOT_FOUND',
  IGDB_INVALID_PAYLOAD: 'IGDB_INVALID_PAYLOAD',
} as const;

export type ErrorCode = (typeof ERROR_CODES)[keyof typeof ERROR_CODES];
